#!/bin/bash


start() {
 echo "Starting external IP tracking"

	nohup /bin/track_ip 2>&1 > /tmp/track_ip.log &
	echo $! > /tmp/track_ip.pid

}
stop() {
	echo "Stopping track_ip"
	kill  `cat /tmp/track_ip.pid`	

}
status() {

	tail -f /tmp/track_ip.log

}


case "$1" in
 start)
 start
 ;;
 stop)
 stop
 ;;
 restart|reload|force-reload)
 stop
 start
 ;;
 status)
 status
 ;;
 *)
 echo "Usage: track_ip_service {start|stop|status}"
 exit 1
 esac
exit 0 


